### ISSUE TITLE
詰まったところ

### ISSUE THREAD

**Issue by Komei22** [Komei22/rails-tutorial#1]
# localhost:3000にアクセスできない問題
## 状況
rails newしてhelloworldのアクションとroutesを追記し、rails sをした
しかし、localhost:3000にアクセスできない
ターミナルにアクセスログも来ない

## 原因
前のサーバーのプロセスが残っていた

## 対処
1. 実行されているプロセスでrailsのプロセスが走っていないかを確認
1. あった場合はそれをkill
1. 再度rails sで立て直す

ここまでの対処で解消できたらよかったが、解消されていなかった。
そこで、
/アプリケーションディレクトリ/tmp/pids/server.pid.
を確認した。
すると、pidが残っていたのでそれを削除。
killしても消されない場合があるので注意。

**Comment by Asuforce** [comment]
rails server を止める時 `crrl + c`を使ってると思う。
この時のシグナルを kill コマンドで送ってみると、より深い検証ができそう
http://equj65.net/tech/linuxprocessgroup/
