### ISSUE TITLE
Gitの補完が効かなくなった問題

### ISSUE THREAD

**Issue by Komei22** [Komei22/rails-tutorial#24]
## 現象
zsh環境で突然Gitコマンドの補完が効かなくなった。
zshを再起動してもダメ。

## 環境
- zsh5.2
- zplugでプラグイン管理

## 原因
zshを起動時に呼ばれるcompinit関数が読み込む~/.zcompdumpが原因
.zcompdumpはcompinit の実行を高速化するために、ダンプされた設定ファイル

## 解決策
~/.zcompdumpと ~/.zplug/zcompdumpの削除
あれば ~/.zcomdump-コンピュータ名も削除
これを削除することで、.zcompdumpが再生成されるのでGitの補完の設定も再設定される

## 参考
https://github.com/robbyrussell/oh-my-zsh/issues/3996
http://web.archive.org/web/20030620174341/http://dengaku.org/~naoki/zsh/Doc/zsh_19.html#SEC100

**Comment by Asuforce** [comment]
あるある
