### ISSUE TITLE
ch10.3.4 will_paginateのwarning

### ISSUE THREAD

**Issue by Komei22** [Komei22/rails-tutorial#70]
## エラー内容
```
/Users/komei.nomura/dev/sample_app/vendor/bundle/ruby/2.4.0/gems/will_paginate-3.1.5/lib/will_paginate/view_helpers/link_renderer.rb:27: warning: constant ::Fixnum is deprecated
/Users/komei.nomura/dev/sample_app/vendor/bundle/ruby/2.4.0/gems/will_paginate-3.1.5/lib/will_paginate/view_helpers/link_renderer.rb:91: warning: constant ::Fixnum is deprecated
```
warning内容：Fixnumというクラスが非推奨だよ

## 原因
will_paginate5.1.5のバージョンが原因
ruby2.4でFixnumがintegerに統合されたことによって起こった

## 対処
will_paginate3.1.6で改善されているのでアップデート

## 参考
https://github.com/mislav/will_paginate/issues/528

**Comment by Asuforce** [comment]
> will_paginate5.1.5のバージョンによるバグ

バグというとざっくりした印象を受けるので、エラー分を訳すとよさそう〜

ちなみに Fixnum は ruby 2.4 で Integer に統合されたっぽい
http://blog.bigbinary.com/2016/11/18/ruby-2-4-unifies-fixnum-and-bignum-into-integer.html

**Comment by Komei22** [comment]
Warningの内容と原因を追記しました！
