### ISSUE TITLE
Revertについて

### ISSUE THREAD

**Issue by Komei22** [Komei22/rails-tutorial#76]
## GithubでのRevert
Revertとはブランチをマージした後、そのマージを打ち消すために作るプルリクエスト。
間違ったコードを含んだ状態でmasterにマージしてしまった場合に使用する。

## 具体的なRevertの流れ
![revert](https://user-images.githubusercontent.com/28612605/27902232-ed4fb282-626f-11e7-97f5-3067a4176d1d.png)
上の図の流れで修正すると、Masterはバグが入る前の状態に戻せ、かつ、間違ったコードを含んだ状態のTopicを再現できるのでMasterに影響を与えず修正できる。

**Comment by Asuforce** [comment]
青のステータスが「間違ったコードが含まれている状態状態」になってます〜

**Comment by Komei22** [comment]
はずかしい・・・直しました！
